AWSTemplateFormatVersion: "2010-09-09"
Description: "Cloudformation stack that provisions resources to check the CIS compliance of a Windows EC2 Instance"
Parameters:

Mappings:

Conditions:

Resources:
  CustomConfigRule:
    Type: "AWS::Config::ConfigRule"
    Properties:
      ConfigRuleName: CISRule
      Description: A Config rule that performs CIS compliance audit against Linux and Windows EC2 instances
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      Source:
        Owner: CUSTOM_LAMBDA
        SourceIdentifier: !GetAtt LambdaFunction.Arn
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
          - EventSource: aws.config
            MessageType: OversizedConfigurationItemChangeNotification
    DependsOn: LambdaInvokePermissions

  LambdaInvokePermissions:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: config.amazonaws.com

  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: CISRule_Function
      Handler: index.lambda_handler
      Role: !GetAtt LambdaIamRole.Arn
      Runtime: python3.11
      Code:
        ZipFile: |
          Lambda Code

  LambdaIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CISRule_Function_IAMRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSLambdaExecute"
        - "arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole"
      Policies:
        - PolicyName: "ssm-and-config-permission-requirements"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:UpdateInstanceInformation"
                  - "ssm:SendCommand"
                  - "ssm:GetCommandInvocation"
                  - "config:PutEvaluations"
                Resource: "*"

  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: "Check Registry of Instance for compliance"
        parameters:
          commands:
            type: String
            description: "(Required) The commands to run on the instance."
            default: "{{ ssm:CISRule }}"
        mainSteps:
          - precondition:
              StringEquals:
                - platformType
                - Windows
            action: "aws:runPowerShellScript"
            name: "RunCISChecks"
            inputs:
              timeoutSeconds: "60"
              runCommand:
                - |
                  $collection = '{{commands}}'

                  $baseRegistryPath = "HKLM:\"
                  $compliant = 0
                  $nonComplaint = 0

                  $collectionObject = ConvertFrom-Json $collection

                  $version = $collectionObject.Version

                  foreach ($check in $collectionObject.Checks) {
                    $PathParts = ($check.Path).Split(":")
                    $expectedValue = $check.ExpectedValue

                    $registryPath = $PathParts[0]
                    $propertyName = $PathParts[-1]

                    $fullRegistryPath = $baseRegistryPath + $registryPath.Trim()
                      
                    $result = (Get-ItemProperty -Path $fullRegistryPath).$propertyName

                    if ($result -eq $expectedValue) {
                      $compliant++
                    } else {
                      $nonComplaint++
                    }
                  }

                  Write-Host "Completed CIS Checks $version`nRESULT: $compliant compliant and $nonComplaint non-compliant items"
      DocumentFormat: YAML
      DocumentType: Command
      Name: CISRule-Test
      TargetType: "/AWS::EC2::Instance"

  SSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: "text"
      Name: "CISRule"
      Type: "String"
      Value: '
        {
          "Version": "v2.0.0",
          "Checks": [
            {
              "Path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System:DontDisplayLastUserName",
              "ExpectedValue": 0
            },
            {
              "Path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System:EnableLUA",
              "ExpectedValue": 1
            },
            {
              "Path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System:EnableUwpStartupTasks",
              "ExpectedValue": 2
            },
            {
              "Path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System:EnableCursorSuppression",
              "ExpectedValue": 1
            },
            {
              "Path": "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System:ConsentPromptBehaviorAdmin",
              "ExpectedValue": 5
            }
          ]
        }
      '
